# IPython log file

get_ipython().magic('bookmark -b pythons')
get_ipython().magic('bookmark -b python')
get_ipython().magic('bookmark ')
get_ipython().magic('bookmark -l')
get_ipython().magic('bookmark ?>')
get_ipython().magic('pinfo bookmark')
get_ipython().magic('cd pythons')
get_ipython().magic('ls ')
get_ipython().magic('cd Finance&Econometrics/')
get_ipython().magic('run -p user_finan.py')
get_ipython().magic('pycat user_finan.py')
get_ipython().magic('whos ')
resert
resert
get_ipython().magic('reset ')
get_ipython().magic('whos ')
get_ipython().magic('pycat user_finan.py')
get_ipython().magic('whos ')
get_ipython().magic('run -p user_finan.py')
get_ipython().magic('whos ')
get_ipython().magic('pinfo run')
get_ipython().magic('reset ')
get_ipython().magic('run user_finan.py')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
get_ipython().magic('run -n  user_finan.py')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
get_ipython().magic('run user_finan.py')
get_ipython().magic('whos ')
xx
get_ipython().magic('reset ')
get_ipython().magic('run -n  user_finan.py')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
get_ipython().magic('run -t  user_finan.py')
get_ipython().magic('reset ')
get_ipython().magic('run -p  user_finan.py')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
strng="string from Ipython!!"
get_ipython().magic('run -p  user_finan.py')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
strng="string from Ipython!!"
get_ipython().magic('run -t  user_finan.py')
strng
get_ipython().magic('whos ')
get_ipython().magic('reset ')
strng
strng="String from Ipython"
get_ipython().magic('whos ')
get_ipython().magic('run -n  user_finan.py')
get_ipython().magic('run -i  user_finan.py')
get_ipython().magic('pinfo run')
get_ipython().magic('pinfo run')
get_ipython().magic('whos ')
get_ipython().magic('reset strng')
get_ipython().magic('whos ')
remove strng
delete strng
del strng
get_ipython().magic('whos ')
del xx
get_ipython().magic('whos ')
get_ipython().magic('run -p  user_finan.py')
get_ipython().magic('whos ')
strng="this is python"
get_ipython().magic('run -p  user_finan.py')
xx
xx
xx
get_ipython().magic('reset ')
get_ipython().magic('pinfo run')
get_ipython().magic('pycat ~/anaconda/lib/python3.6/site-packages/IPython/core/magics/execution.py')
get_ipython().magic('pinfo run')
clear
import os
get_ipython().magic('pinfo os.rename')
get_ipython().magic('pinfo2 os.rename')
get_ipython().magic('pinfo os.rename')
get_ipython().magic('pinfo os.rename')
get_ipython().magic('psource os.renmae')
get_ipython().magic('psource os.rename')
def xxx(a,b):
    return a+b
xxx 3 4
xxx 3,4
xxx 3, 4
xxx(3,4)
get_ipython().magic('reset ')
get_ipython().magic('whos ')
get_ipython().magic('whos ')
get_ipython().magic('whos ')
get_ipython().magic('whos ')
get_ipython().magic('whos ')
get_ipython().magic('ls ')
get_ipython().magic('whos ')
get_ipython().magic('whos ')
wos
get_ipython().magic('who ')
get_ipython().magic('whos ')
get_ipython().magic('ls ')
get_ipython().magic('cd programms')
get_ipython().magic('cd programs')
get_ipython().magic('ls ')
get_ipython().magic('cd -1')
get_ipython().magic('ls ')
get_ipython().magic('cd ~')
get_ipython().magic('ls ')
get_ipython().magic('cd Documents/')
get_ipython().magic('cd OneDrive\\ -\\ myownBsns')
get_ipython().magic('cd 同步盘/')
get_ipython().magic('ls ')
get_ipython().magic('cd Jupyter/')
get_ipython().magic('ls ')
get_ipython().magic('bookmark Jupyter')
get_ipython().magic('cd Jupyter')
get_ipython().magic('ls ')
get_ipython().magic('cd pythons')
get_ipython().magic('ls ')
get_ipython().magic('cd Tutorial/')
get_ipython().magic('ls ')
get_ipython().magic('bookmark Tutorial')
get_ipython().magic('cd Tutorial')
get_ipython().magic('ls ')
bookmakr -l
get_ipython().magic('bookmark -l')
get_ipython().magic('ls ')
get_ipython().magic('run 10_Ipython_shell.py')
strng="Lets start here"
get_ipython().magic('run 10_Ipython_shell.py')
get_ipython().magic('run -i 10_Ipython_shell.py')
strng="Let's start here"
get_ipython().magic('run -i 10_Ipython_shell.py')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
get_ipython().magic('whos ')
get_ipython().magic('run -i 10_Ipython_shell.py')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
strng="Let's start here"
get_ipython().magic('run -i 10_Ipython_shell.py')
get_ipython().magic('whos ')
get_ipython().magic('pwd ')
get_ipython().magic('ls ')
get_ipython().magic('ls ')
git status
get_ipython().magic('ls ')
get_ipython().magic('run -i 10_Ipython_shell.py')
get_ipython().magic('whos ')
print "this is good"
get_ipython().magic('whos ')
get_ipython().magic('store strng > /temp/strng.txt')
get_ipython().magic('store strng > strng.txt')
get_ipython().magic('store ')
get_ipython().magic('store strng')
get_ipython().magic('store ')
get_ipython().magic('reset ')
get_ipython().magic('store ')
get_ipython().magic('pinfo store')
get_ipython().magic('store -r')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
get_ipython().magic('store -r')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
get_ipython().magic('whos ')
sotre -r strng
sotre -r strng bar
get_ipython().magic('store -r strng')
get_ipython().magic('whos ')
get_ipython().magic('reset ')
get_ipython().magic('store -r strng')
get_ipython().magic('whos ')
get_ipython().magic('pinfo log')
get_ipython().magic('pinfo logging')
get_ipython().magic('pinfo logstate')
get_ipython().magic('pinfo logging')
get_ipython().magic('pinfo2 logging')
get_ipython().magic('pinfo logstart')
get_ipython().magic('logstart ')
get_ipython().magic('pinfo logstart')
get_ipython().magic('logstart -o mylogging.py')
get_ipython().magic('logoff ')
get_ipython().magic('logstart -o mylogging.py')
get_ipython().magic('logoff ')
logexit
get_ipython().magic('logonstop')
logonstop
get_ipython().magic('logstop ')
get_ipython().magic('logstop ')
